// Auto-generated quiz list - DO NOT EDIT MANUALLY
// Generated by GitHub Actions on $(date)

console.log('📁 quiz-links.js laddas...');

const AVAILABLE_QUIZ = [
  {key: 'andra_varldskriget', name: 'Andra världskriget', file: 'Andra världskriget.csv'},
  {key: 'cocktails', name: 'Cocktails', file: 'Cocktails.csv'},
  {key: 'dans', name: 'Dans', file: 'Dans.csv'},
  {key: 'design_och_mode', name: 'Design och mode', file: 'Design och mode.csv'},
  {key: 'disney', name: 'Disney', file: 'Disney.csv'},
  {key: 'djur_och_natur', name: 'Djur och natur', file: 'Djur och natur.csv'},
  {key: 'flaggor', name: 'Flaggor', file: 'Flaggor.csv'},
  {key: 'fotboll', name: 'Fotboll', file: 'Fotboll.csv'},
  {key: 'grundamnen', name: 'Grundämnen', file: 'Grundämnen.csv'},
  {key: 'harry_potter', name: 'Harry Potter', file: 'Harry Potter.csv'},
  {key: 'huvudstader', name: 'Huvudstäder', file: 'Huvudstäder.csv'},
  {key: 'jul', name: 'Jul', file: 'Jul.csv'},
  {key: 'kaffe', name: 'Kaffe', file: 'Kaffe.csv'},
  {key: 'kungligheter', name: 'Kungligheter', file: 'Kungligheter.csv'},
  {key: 'liverpool_fc', name: 'Liverpool FC', file: 'Liverpool FC.csv'},
  {key: 'mat', name: 'Mat', file: 'Mat.csv'},
  {key: 'motor', name: 'Motor', file: 'Motor.csv'},
  {key: 'nfl', name: 'NFL', file: 'NFL.csv'},
  {key: 'nhl', name: 'NHL', file: 'NHL.csv'},
  {key: 'netflix', name: 'Netflix', file: 'Netflix.csv'},
  {key: 'reklam', name: 'Reklam', file: 'Reklam.csv'},
  {key: 'rymden', name: 'Rymden', file: 'Rymden.csv'},
  {key: 'sagan_om_ringen', name: 'Sagan om ringen', file: 'Sagan om ringen.csv'},
  {key: 'sex_and_the_city', name: 'Sex and the City', file: 'Sex and the City.csv'},
  {key: 'spanska_ord', name: 'Spanska ord', file: 'Spanska ord.csv'},
  {key: 'sprak', name: 'Språk', file: 'Språk.csv'},
  {key: 'star_wars', name: 'Star Wars', file: 'Star Wars.csv'},
  {key: 'svenska_synonymer', name: 'Svenska synonymer', file: 'Svenska synonymer.csv'},
  {key: 'sverige', name: 'Sverige', file: 'Sverige.csv'},
  {key: 'vm_1994', name: 'VM 1994', file: 'VM 1994.csv'},
  {key: 'valutor', name: 'Valutor', file: 'Valutor.csv'},
  {key: 'vanner', name: 'Vänner', file: 'Vänner.csv'},
];

// Exportera för användning
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { AVAILABLE_QUIZ };
}

// Logga när filen är klar
console.log('✅ quiz-links.js laddad med', AVAILABLE_QUIZ.length, 'quiz');
console.log('📊 AVAILABLE_QUIZ:', AVAILABLE_QUIZ);
